language: java # can be 'java' if there is no android build target
#android:
#  components:
#    - build-tools-20.0.0
#    - android-20
jdk: openjdk8

# Cache gradle dependencies (should be faster to download them from cache)
cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches/modules-2/files-2.1

# Setup environment
before_install:
- chmod a+x gradlew
- chmod a+x gradle/wrapper/gradle-wrapper.jar

# Default gradle task will be run automatically on build, no need to define it

# Deployment to GitHub-releases
before_deploy:
  - ./gradlew clean
  - ./gradlew build
  - ./gradlew dist
  - ./gradlew desktop:createExe

# deploy:
#   provider: releases
#   api_key:
#     secure: T5Br07Z06r4o92aIxFndXw3Cy/JiCnv+4DuAUvXQAgo/WsLGUVUi2/MuSiQNmi5lWKczvVQLvUoIC9C1P8gxv99w9XhqodR7c/n+SPdFqM8sY7X1zaIOkCkLxYPPgMCdBHGGFcgn7rzzIzQ/jhHKRqJqOwI7wHM7AJYBOkXK3AvnxMRfkPDimR3gXgnUImb/TiHlaN6PtWC1uyc3Khy2LK2/vQSa2cduzY/AIh9MX5Qk/uyxrQmINzPx1n1dufJDqgVz7c5lxIsdTb+rTPk9WmV3TgKIb6NLieLe7dZyXWuQKMxkgnwLgEleI/TldIiXXKBZRL/fvkFD5M8zyOFypFbL1EWFLNi2wFh9Masv4WsGdW2OZOErkVRaEC/gPN/Lg84KX7GN6YhnczFbINstP1Om0EQxCImVmglyWBxW3xcyrqfX+3h1OcsugkUtiSFDWVFiKC8j1KDDQRT2QHaX+L8oISuYeAXLuInpxzq3fb2snXE43frU1lmN9PX41tWy3WrWKdFA5STwHB7GVxkR1bvDuFQzGFCb4zPZNRqiyvvt+osUk4NVeWJQU66mqsj+nGg05c46tBVtBETNqszvAB3xAHb27E/W4IGzEdAZPdN4tL3z4UqKoUWI/rA4ARRCKs237wLeZ9NeApI7PhgNPnhGMaQvYP8kNtXgDZyMqxI=
#   file:
#     - "desktop/build/libs/emulio.jar"
#     - "desktop/build/launch4j/emulio.exe"
# #  file:
# #   - "desktop/build/libs/emulio.jar"
# #   - "launch4j/build/emulio.exe"
#   skip_cleanup: true
#   on:
#     tags: true
#     repo: PizzaGames/emulio
deploy:
  provider: releases
  api_key:
    secure: 8AMTgbIjWdpVBkNTza3ZX6D9dLZLg8MJySSv4FiVJwjJU+InNICXGGkegKV+bT8IFupOhs7UJbMVcTjg60ckZTISUcOFpRRSkVCzsMYgWHYAu+lQNp33qdilzhJ/h0V90CxPmTDzMeCt/JTUQVZ2HlPM/7EnV1zDXwgv6tdj7ocFHtsyRsc4jC3tjxvqWhawfAoOpXGipHxwoKT4Z98kXcWSoSVn38oOZ6v3G2PzjMnnZadzEyNmqQ8E8uONxZfj18dKgNqx5PsJzpX/048hNZo3XE9CYjuXq6/01nagodgmoepxI52bH9IGeGGKggLQx1JsP0UahYJjDpanklknqLO7S/52dLnh+sId/6dKpPb8gMy1yAmh16DFZWbYZVb9D6zTY0v9L4tiBE58I3N0W8qcyolCTVQZv7IIZrkpInlPJfscLpq8n+oNrIS67v0/duPXd9Vjo2jLT2JERXejI9mMi84cc2QpXwt/1S5rjknUVi5+LhWAPmb9qEP3UsB0AIW5RbZYz6fm81LQow7nY6mt9iD3dmrfeBSWt9s03ENMKDX7GPr/S+qe6TvcsbILqODCRAuPaMcvQifE1k2q8xrFPEDR9wjOYPumVTBXGz5HMCOl6yy0tk0bqPmj+GdRFttNIkI5GV3PPWz6qBiouUPULqkRQUl8bpoLkjuUjLU=
  file: 
    - desktop/build/libs/emulio.jar
    - launch4j/build/emulio.exe
  on:
    repo: PizzaGames/emulio
