/**
* TheGamesDB API
* API Documentations
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.github.emulio.scrapers.thegamesdb.clientAutoGenerated.models


import com.squareup.moshi.Json



/**
 * 
 * @param editId 
 * @param type 
 * @param value 
 * @param gameId 
 * @param timestamp 
 */

data class GamesUpdatesDataUpdates (
    @Json(name = "edit_id")
    val editId: kotlin.Int? = null,
    @Json(name = "type")
    val type: kotlin.String? = null,
    @Json(name = "value")
    val value: kotlin.String? = null,
    @Json(name = "game_id")
    val gameId: kotlin.Int? = null,
    @Json(name = "timestamp")
    val timestamp: kotlin.String? = null
) {

}

