/**
* TheGamesDB API
* API Documentations
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.github.emulio.scrapers.thegamesdb.clientAutoGenerated.models

import com.squareup.moshi.Json



/**
 * 
 * @param boxart 
 * @param platform 
 */

data class GamesByGameIDInclude (
    @Json(name = "boxart")
    val boxart: GamesByGameIDIncludeBoxart,
    @Json(name = "platform")
    val platform: GamesByGameIDIncludePlatform
) {

}

