/**
* TheGamesDB API
* API Documentations
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.github.emulio.scrapers.thegamesdb.clientAutoGenerated.models

import com.squareup.moshi.Json

/**
 * 
 * @param _22 
 * @param _1 
 * @param _14 
 * @param _15 
 * @param _4920 
 */

data class GamesByGameNameIncludePlatform (
    @Json(name = "data")
    val data: Any
)
