/**
* TheGamesDB API
* API Documentations
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.github.emulio.scrapers.thegamesdb.clientAutoGenerated.models

import com.squareup.moshi.Json



/**
 * 
 * @param _12 
 * @param _13 
 * @param _14 
 */

data class GamesByPlatformIDIncludePlatformData (
    @Json(name = "12")
    val data: Any
) {

}

