/**
* TheGamesDB API
* API Documentations
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.github.emulio.scrapers.thegamesdb.clientAutoGenerated.models


import com.squareup.moshi.Json



/**
 * 
 * @param youtube 
 * @param overview 
 * @param lastUpdated 
 * @param coop 
 * @param os 
 * @param developers 
 * @param players 
 * @param sound 
 * @param rating 
 * @param hdd 
 * @param gameTitle 
 * @param video 
 * @param processor 
 * @param alternates 
 * @param platform 
 * @param releaseDate 
 * @param genres 
 * @param publishers 
 * @param id 
 * @param ram 
 */

data class GamesByGameIDDataGames (
    @Json(name = "youtube")
    val youtube: kotlin.String? = null,
    @Json(name = "overview")
    val overview: kotlin.String? = null,
    @Json(name = "last_updated")
    val lastUpdated: kotlin.String? = null,
    @Json(name = "coop")
    val coop: kotlin.String? = null,
    @Json(name = "os")
    val os: kotlin.String? = null,
    @Json(name = "developers")
    val developers: kotlin.collections.List<kotlin.Int>? = null,
    @Json(name = "players")
    val players: kotlin.Int? = null,
    @Json(name = "sound")
    val sound: kotlin.String? = null,
    @Json(name = "rating")
    val rating: kotlin.String? = null,
    @Json(name = "hdd")
    val hdd: kotlin.String? = null,
    @Json(name = "game_title")
    val gameTitle: kotlin.String? = null,
    @Json(name = "video")
    val video: kotlin.String? = null,
    @Json(name = "processor")
    val processor: kotlin.String? = null,
    @Json(name = "alternates")
    val alternates: kotlin.collections.List<kotlin.String>? = null,
    @Json(name = "platform")
    val platform: kotlin.Int? = null,
    @Json(name = "release_date")
    val releaseDate: kotlin.String? = null,
    @Json(name = "genres")
    val genres: kotlin.collections.List<kotlin.Int>? = null,
    @Json(name = "publishers")
    val publishers: kotlin.collections.List<kotlin.Int>? = null,
    @Json(name = "id")
    val id: kotlin.Int? = null,
    @Json(name = "ram")
    val ram: kotlin.String? = null
) {

}

