/**
* TheGamesDB API
* API Documentations
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.github.emulio.scrapers.thegamesdb.clientAutoGenerated.models


import com.squareup.moshi.Json



/**
 * 
 * @param images 
 * @param count 
 * @param baseUrl 
 */

data class PlatformsImagesData (
    @Json(name = "images")
    val images: Any,
    @Json(name = "count")
    val count: kotlin.Int,
    @Json(name = "base_url")
    val baseUrl: GamesByGameIDIncludeBoxartBaseUrl
) {

}

