!!com.github.emulio.model.EmulioConfig {
  debug: true,
  gamepadConfig: {
    Controller (XBOX 360 For Windows): {
      axisTrigger: 4,
      axisX: 0,
      axisY: 1,
      cancel: 1,
      confirm: 0,
      down: 12,
      exit: -1,
      find: 3,
      left: 13,
      name: Controller (XBOX 360 For Windows),
      options: 7,
      pageDown: 5,
      pageUp: 4,
      right: 11,
      select: 6,
      type: JOYSTICK,
      up: 10,
      usePov: true
    }
  },
  graphicsConfig: {
    fullscreen: false,
    screenHeight: 720,
    screenWidth: 1280,
    vsync: true
  },
  keyboardConfig: {
    axisTrigger: -1,
    axisX: -1,
    axisY: -1,
    cancel: 52,
    confirm: 54,
    down: 20,
    exit: 131,
    find: 246,
    left: 21,
    name: Keyboard,
    options: 67,
    pageDown: 93,
    pageUp: 92,
    right: 22,
    select: 44,
    type: KEYBOARD,
    up: 19,
    usePov: false
  },
  languagePath: /languages/emulio-language-en_US.yaml,
  maxGamesList: 200,
  uiConfig: {
    screenSaver: null,
    themeName: null,
    transitionsType: null
  }
}
