!!com.github.emulio.model.EmulioConfig {
  debug: true,
  gamepadConfig: {
    },
  graphicsConfig: {
    fullscreen: null,
    screenHeight: null,
    screenWidth: null,
    vsync: null
  },
  keyboardConfig: {
    LTrigger: -1,
    RTrigger: -1,
    axisX: -1,
    axisY: -1,
    cancel: 52,
    confirm: 54,
    down: 20,
    exit: 131,
    find: 246,
    left: 21,
    name: Keyboard,
    options: 67,
    pageDown: 93,
    pageUp: 92,
    right: 22,
    select: 44,
    type: KEYBOARD,
    up: 19
  },
  uiConfig: {
    screenSaver: null,
    themeName: null,
    transitionsType: null
  }
}
