!!com.github.emulio.model.EmulioConfig {
  debug: true,
  gamepadConfig: {
    Controller (XBOX 360 For Windows): {
      axisTrigger: 4,
      axisX: 1,
      axisY: 0,
      cancel: 1,
      confirm: 0,
      down: -1,
      exit: -1,
      find: 3,
      left: -1,
      name: Controller (XBOX 360 For Windows),
      options: 7,
      pageDown: 5,
      pageUp: 4,
      right: -1,
      select: 8,
      type: JOYSTICK,
      up: -1
    }
  },
  graphicsConfig: {
    fullscreen: null,
    screenHeight: null,
    screenWidth: null,
    vsync: null
  },
  keyboardConfig: {
    axisTrigger: -1,
    axisX: -1,
    axisY: -1,
    cancel: 52,
    confirm: 54,
    down: 20,
    exit: 131,
    find: 246,
    left: 21,
    name: Keyboard,
    options: 67,
    pageDown: 93,
    pageUp: 92,
    right: 22,
    select: 44,
    type: KEYBOARD,
    up: 19
  },
  uiConfig: {
    screenSaver: null,
    themeName: null,
    transitionsType: null
  }
}
