package com.github.emulio.scrapers.thegamesdb.clientAutoGenerated.infrastructure

/**
 * Provides enumerated HTTP verbs
 */
enum class RequestMethod {
    GET, DELETE, HEAD, OPTIONS, PATCH, POST, PUT
}